In [1]:
%pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ----------------- ---------------------- 3.7/8.3 MB 20.7 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 23.9 MB/s  0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------------------- ------------------ 6.8/12.6 MB 33.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 35.0 MB/s  0:00:00
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   ---------------- ----------------------- 15.5/37.4 MB 74.4 MB/s eta 0:00:01
   ------------------------------------- -- 35.1/37.4 MB 84.8 MB/s eta 0:00:01
   ---------------------------------------- 37.4/37.4 MB 66.4 MB/s  0:00:00

   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   --

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "gosto de machine learning",
    "machine learning é incrivel",
    "gosto de programar"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Vocabulário:")
print(vectorizer.get_feature_names_out())

print("\nMatriz:")
print(X.toarray())


Vocabulário:
['de' 'gosto' 'incrivel' 'learning' 'machine' 'programar']

Matriz:
[[1 1 0 1 1 0]
 [0 0 1 1 1 0]
 [1 1 0 0 0 1]]
